name: Trigger auto deployment for robyn-portfolio

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/robyn-portfolio-AutoDeployTrigger-ade86804-bd62-479d-a1a2-2219ca52b279.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: elestriel.azurecr.io
          username: ${{ secrets.ROBYNPORTFOLIO_REGISTRY_USERNAME }}
          password: ${{ secrets.ROBYNPORTFOLIO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: elestriel.azurecr.io/robyn-portfolio:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ROBYNPORTFOLIO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n robyn-portfolio -g Robyn --server elestriel.azurecr.io --username  ${{ secrets.ROBYNPORTFOLIO_REGISTRY_USERNAME }} --password ${{ secrets.ROBYNPORTFOLIO_REGISTRY_PASSWORD }}
            az containerapp update -n robyn-portfolio -g Robyn --image elestriel.azurecr.io/robyn-portfolio:${{ github.sha }}
     

